# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import library_pb2 as proto_dot_library__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibraryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBook = channel.unary_unary(
                '/library.LibraryService/GetBook',
                request_serializer=proto_dot_library__pb2.GetBookRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Book.FromString,
                _registered_method=True)
        self.ListBooks = channel.unary_unary(
                '/library.LibraryService/ListBooks',
                request_serializer=proto_dot_library__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_library__pb2.BookList.FromString,
                _registered_method=True)
        self.AddBook = channel.unary_unary(
                '/library.LibraryService/AddBook',
                request_serializer=proto_dot_library__pb2.Book.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Book.FromString,
                _registered_method=True)
        self.PartialUpdateBook = channel.unary_unary(
                '/library.LibraryService/PartialUpdateBook',
                request_serializer=proto_dot_library__pb2.Book.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Book.FromString,
                _registered_method=True)
        self.DeleteBook = channel.unary_unary(
                '/library.LibraryService/DeleteBook',
                request_serializer=proto_dot_library__pb2.GetBookRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Empty.FromString,
                _registered_method=True)
        self.BorrowBook = channel.unary_unary(
                '/library.LibraryService/BorrowBook',
                request_serializer=proto_dot_library__pb2.BorrowBookRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Borrowing.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/library.LibraryService/ReturnBook',
                request_serializer=proto_dot_library__pb2.ReturnBookRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.ReturnBookResponse.FromString,
                _registered_method=True)
        self.AddMember = channel.unary_unary(
                '/library.LibraryService/AddMember',
                request_serializer=proto_dot_library__pb2.Member.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Member.FromString,
                _registered_method=True)
        self.ListMembers = channel.unary_unary(
                '/library.LibraryService/ListMembers',
                request_serializer=proto_dot_library__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_library__pb2.MemberList.FromString,
                _registered_method=True)
        self.GetMember = channel.unary_unary(
                '/library.LibraryService/GetMember',
                request_serializer=proto_dot_library__pb2.GetMemberRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Member.FromString,
                _registered_method=True)
        self.UpdateMember = channel.unary_unary(
                '/library.LibraryService/UpdateMember',
                request_serializer=proto_dot_library__pb2.Member.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Member.FromString,
                _registered_method=True)
        self.DeleteMember = channel.unary_unary(
                '/library.LibraryService/DeleteMember',
                request_serializer=proto_dot_library__pb2.GetMemberRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Empty.FromString,
                _registered_method=True)
        self.ListBorrowings = channel.unary_unary(
                '/library.LibraryService/ListBorrowings',
                request_serializer=proto_dot_library__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_library__pb2.BorrowingList.FromString,
                _registered_method=True)
        self.GetBorrowing = channel.unary_unary(
                '/library.LibraryService/GetBorrowing',
                request_serializer=proto_dot_library__pb2.GetBorrowingRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Borrowing.FromString,
                _registered_method=True)
        self.ListBorrowingsByMember = channel.unary_unary(
                '/library.LibraryService/ListBorrowingsByMember',
                request_serializer=proto_dot_library__pb2.GetMemberRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.BorrowingList.FromString,
                _registered_method=True)
        self.ListBorrowingsByBook = channel.unary_unary(
                '/library.LibraryService/ListBorrowingsByBook',
                request_serializer=proto_dot_library__pb2.GetBookRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.BorrowingList.FromString,
                _registered_method=True)


class LibraryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrowBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBorrowings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBorrowing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBorrowingsByMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBorrowingsByBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBook,
                    request_deserializer=proto_dot_library__pb2.GetBookRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Book.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=proto_dot_library__pb2.Empty.FromString,
                    response_serializer=proto_dot_library__pb2.BookList.SerializeToString,
            ),
            'AddBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBook,
                    request_deserializer=proto_dot_library__pb2.Book.FromString,
                    response_serializer=proto_dot_library__pb2.Book.SerializeToString,
            ),
            'PartialUpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdateBook,
                    request_deserializer=proto_dot_library__pb2.Book.FromString,
                    response_serializer=proto_dot_library__pb2.Book.SerializeToString,
            ),
            'DeleteBook': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBook,
                    request_deserializer=proto_dot_library__pb2.GetBookRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Empty.SerializeToString,
            ),
            'BorrowBook': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowBook,
                    request_deserializer=proto_dot_library__pb2.BorrowBookRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Borrowing.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=proto_dot_library__pb2.ReturnBookRequest.FromString,
                    response_serializer=proto_dot_library__pb2.ReturnBookResponse.SerializeToString,
            ),
            'AddMember': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMember,
                    request_deserializer=proto_dot_library__pb2.Member.FromString,
                    response_serializer=proto_dot_library__pb2.Member.SerializeToString,
            ),
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=proto_dot_library__pb2.Empty.FromString,
                    response_serializer=proto_dot_library__pb2.MemberList.SerializeToString,
            ),
            'GetMember': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMember,
                    request_deserializer=proto_dot_library__pb2.GetMemberRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Member.SerializeToString,
            ),
            'UpdateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMember,
                    request_deserializer=proto_dot_library__pb2.Member.FromString,
                    response_serializer=proto_dot_library__pb2.Member.SerializeToString,
            ),
            'DeleteMember': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMember,
                    request_deserializer=proto_dot_library__pb2.GetMemberRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Empty.SerializeToString,
            ),
            'ListBorrowings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBorrowings,
                    request_deserializer=proto_dot_library__pb2.Empty.FromString,
                    response_serializer=proto_dot_library__pb2.BorrowingList.SerializeToString,
            ),
            'GetBorrowing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBorrowing,
                    request_deserializer=proto_dot_library__pb2.GetBorrowingRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Borrowing.SerializeToString,
            ),
            'ListBorrowingsByMember': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBorrowingsByMember,
                    request_deserializer=proto_dot_library__pb2.GetMemberRequest.FromString,
                    response_serializer=proto_dot_library__pb2.BorrowingList.SerializeToString,
            ),
            'ListBorrowingsByBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBorrowingsByBook,
                    request_deserializer=proto_dot_library__pb2.GetBookRequest.FromString,
                    response_serializer=proto_dot_library__pb2.BorrowingList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.LibraryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.LibraryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LibraryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/GetBook',
            proto_dot_library__pb2.GetBookRequest.SerializeToString,
            proto_dot_library__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListBooks',
            proto_dot_library__pb2.Empty.SerializeToString,
            proto_dot_library__pb2.BookList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/AddBook',
            proto_dot_library__pb2.Book.SerializeToString,
            proto_dot_library__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PartialUpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/PartialUpdateBook',
            proto_dot_library__pb2.Book.SerializeToString,
            proto_dot_library__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/DeleteBook',
            proto_dot_library__pb2.GetBookRequest.SerializeToString,
            proto_dot_library__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrowBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/BorrowBook',
            proto_dot_library__pb2.BorrowBookRequest.SerializeToString,
            proto_dot_library__pb2.Borrowing.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ReturnBook',
            proto_dot_library__pb2.ReturnBookRequest.SerializeToString,
            proto_dot_library__pb2.ReturnBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/AddMember',
            proto_dot_library__pb2.Member.SerializeToString,
            proto_dot_library__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListMembers',
            proto_dot_library__pb2.Empty.SerializeToString,
            proto_dot_library__pb2.MemberList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/GetMember',
            proto_dot_library__pb2.GetMemberRequest.SerializeToString,
            proto_dot_library__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/UpdateMember',
            proto_dot_library__pb2.Member.SerializeToString,
            proto_dot_library__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/DeleteMember',
            proto_dot_library__pb2.GetMemberRequest.SerializeToString,
            proto_dot_library__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBorrowings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListBorrowings',
            proto_dot_library__pb2.Empty.SerializeToString,
            proto_dot_library__pb2.BorrowingList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBorrowing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/GetBorrowing',
            proto_dot_library__pb2.GetBorrowingRequest.SerializeToString,
            proto_dot_library__pb2.Borrowing.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBorrowingsByMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListBorrowingsByMember',
            proto_dot_library__pb2.GetMemberRequest.SerializeToString,
            proto_dot_library__pb2.BorrowingList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBorrowingsByBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListBorrowingsByBook',
            proto_dot_library__pb2.GetBookRequest.SerializeToString,
            proto_dot_library__pb2.BorrowingList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
